#!/bin/sh

set -e

if [ -x /share/extract-bbr/extract-bbr.pl -a -r /share/extract-bbr/extract-bbr.conf ]
then
    status="$(/share/extract-bbr/extract-bbr.pl)"
    if [ -n "${status}" ]
    then
        /usr/bin/logger -p cron.info -t extract-bbr "updated dictionary (read/written records: ${status})."
    else
        /usr/bin/logger -p cron.info -t extract-bbr "no dictionary update necessary."
    fi
fi

exit 0
